### ISSUE TITLE
Version 0.15.0 : DLL load failed - works with 0.14.1

### ISSUE THREAD

**Issue by TormodLandet** [conda-forge/pyarrow-feedstock#87] opened 2019-10-15 15:55 UTC
Problem: the latest pyarrow version fails to load (ImportError due to DLL error).

### Minimum non-working example

```cmd
conda create -n test1 python=3 pyarrow=0.15.0
conda activate test1
python -c "import platform; print(platform.platform()); import pyarrow"
```
The output from the last command is
```
Windows-10-10.0.17763-SP0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\test1\lib\site-packages\pyarrow\__init__.py", line 49, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: DLL load failed: The specified module could not be found.
```
Output from `conda list`:
```
# packages in environment at C:\Anaconda3\envs\test1:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.15.0           py37h00ef551_1    https://conda.anaconda.org/conda-forge
blas                      1.0                         mkl
boost-cpp                 1.70.0               h6a4c333_2    https://conda.anaconda.org/conda-forge
brotli                    1.0.7                h33f27b4_0
bzip2                     1.0.8                he774522_0
c-ares                    1.15.0            h62dcd97_1001
ca-certificates           2019.8.28                     0
certifi                   2019.9.11                py37_0
double-conversion         3.1.5                ha925a31_1
gflags                    2.2.2                ha925a31_0
glog                      0.4.0                h33f27b4_0
grpc-cpp                  1.23.0               h4d7d3fa_0    https://conda.anaconda.org/conda-forge
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.4                      245
libprotobuf               3.8.0                h7bd577a_0
lz4-c                     1.8.3             he025d50_1001    https://conda.anaconda.org/conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.14           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0
openssl                   1.1.1d               he774522_2
pandas                    0.25.1           py37ha925a31_0
parquet-cpp               1.5.1                         2    https://conda.anaconda.org/conda-forge
pip                       19.2.3                   py37_0
pyarrow                   0.15.0           py37h803c963_0    https://conda.anaconda.org/conda-forge
python                    3.7.4                h5263a28_0
python-dateutil           2.8.0                    py37_0
pytz                      2019.3                     py_0
re2                       2019.09.01       vc14h6538335_0  [vc14]  https://conda.anaconda.org/conda-forge
setuptools                41.4.0                   py37_0
six                       1.12.0                   py37_0
snappy                    1.1.7                h777316e_3
sqlite                    3.30.0               he774522_0
thrift-cpp                0.12.0            hd042d19_1004    https://conda.anaconda.org/conda-forge
uriparser                 0.9.3                he025d50_1    https://conda.anaconda.org/conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.4.3                hd8a0e53_0    https://conda.anaconda.org/conda-forge
```

### Minimum working example, using the previous version of pyarrow

```cmd
conda create -n test2 python=3 pyarrow=0.14.1
conda activate test2
python -c "import platform; print(platform.platform()); import pyarrow"
```
This outputs `Windows-10-10.0.17763-SP0` without any subsequent ImportError

The output from `conda list`:
```
# packages in environment at C:\Anaconda3\envs\test2:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.14.1           py37h5c295ed_4    https://conda.anaconda.org/conda-forge
blas                      1.0                         mkl
boost-cpp                 1.70.0               h6a4c333_2    https://conda.anaconda.org/conda-forge
brotli                    1.0.7                h33f27b4_0
bzip2                     1.0.8                he774522_0
c-ares                    1.15.0            h62dcd97_1001
ca-certificates           2019.8.28                     0
certifi                   2019.9.11                py37_0
double-conversion         3.1.5                ha925a31_1
gflags                    2.2.2                ha925a31_0
glog                      0.4.0                h33f27b4_0
grpc-cpp                  1.23.0               h4d7d3fa_0    https://conda.anaconda.org/conda-forge
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.4                      245
libprotobuf               3.8.0                h7bd577a_0
lz4-c                     1.8.3             he025d50_1001    https://conda.anaconda.org/conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.14           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0
openssl                   1.1.1d               he774522_2
pandas                    0.25.1           py37ha925a31_0
parquet-cpp               1.5.1                         2    https://conda.anaconda.org/conda-forge
pip                       19.2.3                   py37_0
pyarrow                   0.14.1           py37h803c963_2    https://conda.anaconda.org/conda-forge
python                    3.7.4                h5263a28_0
python-dateutil           2.8.0                    py37_0
pytz                      2019.3                     py_0
re2                       2019.09.01       vc14h6538335_0  [vc14]  https://conda.anaconda.org/conda-forge
setuptools                41.4.0                   py37_0
six                       1.12.0                   py37_0
snappy                    1.1.7                h777316e_3
sqlite                    3.30.0               he774522_0
thrift-cpp                0.12.0            hd042d19_1004    https://conda.anaconda.org/conda-forge
uriparser                 0.9.3                he025d50_1    https://conda.anaconda.org/conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.4.0                hd8a0e53_0    https://conda.anaconda.org/conda-forge
```

**Comment by wesm** [comment] 2019-10-15 16:54
You are mixing packages from defaults and conda-forge, which is not supported. You need to use `-c conda-forge` when creating the environment. You can make conda-forge the highest priority channel with

`conda config --add channels conda-forge`

Can you try this and let us know if it resolves the issue?

**Comment by TormodLandet** [comment] 2019-10-16 07:08
Thanks for your swift feedback! I tried the following:

```cmd
conda create -n test3 -c https://conda.anaconda.org/conda-forge python=3 pyarrow=0.15.0
conda activate test3
python -c "import platform; print(platform.platform()); import pyarrow"
```

The output is still
```
Windows-10-10.0.17763-SP0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\test3\lib\site-packages\pyarrow\__init__.py", line 49, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: DLL load failed: The specified module could not be found.
```

Here is `conda list`:

```
# packages in environment at C:\Anaconda3\envs\test3:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.15.0           py37h00ef551_1    https://conda.anaconda.org/conda-forge
boost-cpp                 1.70.0               h6a4c333_2    https://conda.anaconda.org/conda-forge
brotli                    1.0.7             he025d50_1000    https://conda.anaconda.org/conda-forge
bzip2                     1.0.8                hfa6e2cd_1    https://conda.anaconda.org/conda-forge
c-ares                    1.15.0            h2fa13f4_1001    https://conda.anaconda.org/conda-forge
ca-certificates           2019.9.11            hecc5488_0    https://conda.anaconda.org/conda-forge
certifi                   2019.6.16                py37_1    https://conda.anaconda.org/conda-forge
double-conversion         3.1.5                h6538335_1    https://conda.anaconda.org/conda-forge
gflags                    2.2.2             he025d50_1001    https://conda.anaconda.org/conda-forge
glog                      0.4.0                he025d50_1    https://conda.anaconda.org/conda-forge
grpc-cpp                  1.23.0               h4d7d3fa_0    https://conda.anaconda.org/conda-forge
intel-openmp              2019.4                      245
libblas                   3.8.0                    14_mkl    https://conda.anaconda.org/conda-forge
libcblas                  3.8.0                    14_mkl    https://conda.anaconda.org/conda-forge
liblapack                 3.8.0                    14_mkl    https://conda.anaconda.org/conda-forge
libprotobuf               3.8.0                h1a1b453_0    https://conda.anaconda.org/conda-forge
lz4-c                     1.8.3             he025d50_1001    https://conda.anaconda.org/conda-forge
mkl                       2019.4                      245
numpy                     1.17.1           py37hc71023c_0    https://conda.anaconda.org/conda-forge
openssl                   1.1.1c               hfa6e2cd_0    https://conda.anaconda.org/conda-forge
pandas                    0.25.1           py37he350917_0    https://conda.anaconda.org/conda-forge
parquet-cpp               1.5.1                         2    https://conda.anaconda.org/conda-forge
pip                       19.3                     py37_0    https://conda.anaconda.org/conda-forge
pyarrow                   0.15.0           py37h803c963_0    https://conda.anaconda.org/conda-forge
python                    3.7.3                h510b542_1    https://conda.anaconda.org/conda-forge
python-dateutil           2.8.0                      py_0    https://conda.anaconda.org/conda-forge
pytz                      2019.3                     py_0    https://conda.anaconda.org/conda-forge
re2                       2019.09.01       vc14h6538335_0  [vc14]  https://conda.anaconda.org/conda-forge
setuptools                41.4.0                   py37_0    https://conda.anaconda.org/conda-forge
six                       1.12.0                py37_1000    https://conda.anaconda.org/conda-forge
snappy                    1.1.7             h6538335_1002    https://conda.anaconda.org/conda-forge
sqlite                    3.30.1               hfa6e2cd_0    https://conda.anaconda.org/conda-forge
thrift-cpp                0.12.0            hd042d19_1004    https://conda.anaconda.org/conda-forge
uriparser                 0.9.3                he025d50_1    https://conda.anaconda.org/conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0    https://conda.anaconda.org/conda-forge
wincertstore              0.2                   py37_1002    https://conda.anaconda.org/conda-forge
xz                        5.2.4             h2fa13f4_1001    https://conda.anaconda.org/conda-forge
zlib                      1.2.11            h2fa13f4_1006    https://conda.anaconda.org/conda-forge
zstd                      1.4.3                hd8a0e53_0    https://conda.anaconda.org/conda-forge
```

The following packages are still not from conda-forge for some reason:
```
intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
mkl                pkgs/main/win-64::mkl-2019.4-245
vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_0
```

**Comment by wesm** [comment] 2019-10-29 16:30
@ocefpaf @jakirkham any ideas about how we could debug this? I'm unable to reproduce the issue myself

**Comment by saschahofmann** [comment] 2019-10-30 11:22
We are generating our environment from file.  Is 
```
channels:
  - conda-forge
```
doing the same as
```
conda config --add channels conda-forge
```
?

**Comment by xhochy** [comment] 2019-10-30 14:06
> We are generating our environment from file. Is
> 
> ```
> channels:
>   - conda-forge
> ```
> 
> doing the same as
> 
> ```
> conda config --add channels conda-forge
> ```
> 
> ?

Yes, but using `--prepend` is better as `conda-forge` should be before defaults. 

@saschahofmann @TormodLandet Which version of anaconda/miniconda are you using? Can you add the output of `conda info` here, please?

**Comment by saschahofmann** [comment] 2019-10-30 14:14
the active environment is created with the mentioned channel setting. Should it show up in the channel URLs

**Comment by xhochy** [comment] 2019-10-30 14:22
@saschahofmann The `conda info` is from OSX but the issue here is about Windows. 🤔

**Comment by saschahofmann** [comment] 2019-10-30 14:30
Upsi my bad. Here is the output from the Windows machine:
```

**Comment by ocefpaf** [comment] 2019-10-30 14:56
> @ocefpaf @jakirkham any ideas about how we could debug this? I'm unable to reproduce the issue myself

Windows is not trivial to debug. Like @xhochy mentioned be sure to have conda-forge on top of defaults in your condarc and try both with and without strict. (My envs work better 99% of the time with `strict` enabled but there are some corner cases.)

**Comment by saschahofmann** [comment] 2019-10-30 15:00
Do you know whether  the channel setting environment.yaml is appended or prepended?
Could I force it to prepend it by doing something like:
```
channels:
  - conda-forge
  - default
```

**Comment by ocefpaf** [comment] 2019-10-30 15:31
The channel in the `environemnt.yaml` should be enough.

~~You may have your `.condarc` in a non-writable directory and that may be the culprit in the failure to add it via the command.~~

Not really `C:\Users\gyana\.condarc` should be writable to you b/c that is a users directory, right?

**Comment by saschahofmann** [comment] 2019-10-30 15:37
Yes

**Comment by saschahofmann** [comment] 2019-10-30 15:39
Yes. Plus when I do run `conda config --prepend channels conda-forge` it is added to the `conda config` output (the same happens on mac).

**Comment by saschahofmann** [comment] 2019-10-30 15:50
I am gonna recreate the environment with conda-forge prepended and see whether the dll error still occurs.

**Comment by saschahofmann** [comment] 2019-10-30 16:32
Ok, still getting the dll error. Will go with the pip version for now.

**Comment by kszucs** [comment] 2020-02-23 19:03
@saschahofmann may we close this issue?

**Comment by saschahofmann** [comment] 2020-02-24 09:34
Yes. We stopped using Windows plus the pip version did the trick until then!

**Closed** 2020-02-24 09:46 UTC
